name: foodie-map CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install poetry
          python -m poetry install
      - name: Run Python Lint and Tests
        run: |
          flake8 .
          python manage.py test main

  deploy:
    needs: [lint-test-python]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        if: github.ref == 'refs/heads/master'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"